#pragma once

/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_github_boogiemonster1o1_mcnotify_provider_WindowsProvider_Native */

#ifndef _Included_io_github_boogiemonster1o1_mcnotify_provider_WindowsProvider_Native
#define _Included_io_github_boogiemonster1o1_mcnotify_provider_WindowsProvider_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_boogiemonster1o1_mcnotify_provider_WindowsProvider_Native
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_io_github_boogiemonster1o1_mcnotify_provider_WindowsProvider_00024Native_init
  (JNIEnv *, jclass);

/*
 * Class:     io_github_boogiemonster1o1_mcnotify_provider_WindowsProvider_Native
 * Method:    sendNotification
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_boogiemonster1o1_mcnotify_provider_WindowsProvider_00024Native_sendNotification
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_boogiemonster1o1_mcnotify_provider_WindowsProvider_Native
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_boogiemonster1o1_mcnotify_provider_WindowsProvider_00024Native_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
